// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
  THUMBNAIL_QUEUE: Queue<ThumbnailJobMessage>;
}

/**
 * 書影取得ジョブのメッセージ
 */
type ThumbnailJobMessage = {
  bookId: string;
  isbn: string;
};
