// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
  THUMBNAIL_QUEUE: Queue<ThumbnailJobMessage>;
  RAKUTEN_APP_ID: string;
  RAKUTEN_APP_SECRET: string;
  BETTER_AUTH_URL: string;
}

/**
 * 書影取得ジョブのメッセージ
 */
type ThumbnailJobMessage = {
  bookId: string;
  isbn: string;
};
