name: Build Check

on:
  push:
    branches-ignore: [main, gh-pages]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Build
        run: bun run build
