name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: ./.github/actions/setup-bun

      - name: Run test
        run: bun test
