name: Trigger Update Books

on:
  workflow_dispatch:
  schedule:
    # 日本時間 金曜日の24時
    - cron: "0 15 * * 5"

jobs:
  trigger-update-books:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true

      - name: Run script
        run: bun ./scripts/trigger-update-books.ts
        env:
          API_SECRET_KEY: ${{ secrets.PROD_API_SECRET_KEY }}
