name: Trigger Update Books

on:
  workflow_dispatch:
  schedule:
    # 日本時間 金曜日の24時
    - cron: "0 15 * * 5"

jobs:
  trigger-update-books:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run script
        run: bun ./scripts/trigger-update-books.ts
        env:
          API_SECRET_KEY: ${{ secrets.PROD_API_SECRET_KEY }}
